name: Publish Skeleton
on:
  push:
    branches:
      - dev
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Packaging Dev
        run: |
          npm version --preid dev --git-tag-version false prerelease
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
          pnpm package
          cd package
          npm publish --tag dev
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}